version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/api.dockerfile
    image: plants/api:v1.0
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    image: plants/frontend:v1.0
    container_name: frontend-container
    ports:
      - "8501:8501"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
